/**
 * Libre Graph API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.6.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAICollection_of_user.h
 *
 * 
 */

#ifndef OAICollection_of_user_H
#define OAICollection_of_user_H

#include <QJsonObject>

#include "OAIUser.h"
#include <QList>
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAICollection_of_user : public OAIObject {
public:
    OAICollection_of_user();
    OAICollection_of_user(QString json);
    ~OAICollection_of_user() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QList<OAIUser> getValue() const;
    void setValue(const QList<OAIUser> &value);
    bool is_value_Set() const;
    bool is_value_Valid() const;

    QString getOdataNextLink() const;
    void setOdataNextLink(const QString &odata_next_link);
    bool is_odata_next_link_Set() const;
    bool is_odata_next_link_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QList<OAIUser> value;
    bool m_value_isSet;
    bool m_value_isValid;

    QString odata_next_link;
    bool m_odata_next_link_isSet;
    bool m_odata_next_link_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAICollection_of_user)

#endif // OAICollection_of_user_H
