/**
 * Libre Graph API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.5.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIDirectoryObject.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIDirectoryObject::OAIDirectoryObject(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIDirectoryObject::OAIDirectoryObject() {
    this->initializeModel();
}

OAIDirectoryObject::~OAIDirectoryObject() {}

void OAIDirectoryObject::initializeModel() {

    m_id_isSet = false;
    m_id_isValid = false;

    m_deleted_date_time_isSet = false;
    m_deleted_date_time_isValid = false;
}

void OAIDirectoryObject::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIDirectoryObject::fromJsonObject(QJsonObject json) {

    m_id_isValid = ::OpenAPI::fromJsonValue(id, json[QString("id")]);
    m_id_isSet = !json[QString("id")].isNull() && m_id_isValid;

    m_deleted_date_time_isValid = ::OpenAPI::fromJsonValue(deleted_date_time, json[QString("deletedDateTime")]);
    m_deleted_date_time_isSet = !json[QString("deletedDateTime")].isNull() && m_deleted_date_time_isValid;
}

QString OAIDirectoryObject::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIDirectoryObject::asJsonObject() const {
    QJsonObject obj;
    if (m_id_isSet) {
        obj.insert(QString("id"), ::OpenAPI::toJsonValue(id));
    }
    if (m_deleted_date_time_isSet) {
        obj.insert(QString("deletedDateTime"), ::OpenAPI::toJsonValue(deleted_date_time));
    }
    return obj;
}

QString OAIDirectoryObject::getId() const {
    return id;
}
void OAIDirectoryObject::setId(const QString &id) {
    this->id = id;
    this->m_id_isSet = true;
}

bool OAIDirectoryObject::is_id_Set() const{
    return m_id_isSet;
}

bool OAIDirectoryObject::is_id_Valid() const{
    return m_id_isValid;
}

QDateTime OAIDirectoryObject::getDeletedDateTime() const {
    return deleted_date_time;
}
void OAIDirectoryObject::setDeletedDateTime(const QDateTime &deleted_date_time) {
    this->deleted_date_time = deleted_date_time;
    this->m_deleted_date_time_isSet = true;
}

bool OAIDirectoryObject::is_deleted_date_time_Set() const{
    return m_deleted_date_time_isSet;
}

bool OAIDirectoryObject::is_deleted_date_time_Valid() const{
    return m_deleted_date_time_isValid;
}

bool OAIDirectoryObject::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_deleted_date_time_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIDirectoryObject::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
