/**
 * Open Graph API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIDriveInline.h
 *
 * 
 */

#ifndef OAIDriveInline_H
#define OAIDriveInline_H

#include <QJsonObject>

#include "OAIDriveItem.h"
#include "OAIIdentitySet.h"
#include "OAIQuota.h"
#include <QList>
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIDriveInline : public OAIObject {
public:
    OAIDriveInline();
    OAIDriveInline(QString json);
    ~OAIDriveInline() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getDriveType() const;
    void setDriveType(const QString &drive_type);
    bool is_drive_type_Set() const;
    bool is_drive_type_Valid() const;

    OAIIdentitySet getOwner() const;
    void setOwner(const OAIIdentitySet &owner);
    bool is_owner_Set() const;
    bool is_owner_Valid() const;

    OAIQuota getQuota() const;
    void setQuota(const OAIQuota &quota);
    bool is_quota_Set() const;
    bool is_quota_Valid() const;

    QList<OAIDriveItem> getItems() const;
    void setItems(const QList<OAIDriveItem> &items);
    bool is_items_Set() const;
    bool is_items_Valid() const;

    OAIDriveItem getRoot() const;
    void setRoot(const OAIDriveItem &root);
    bool is_root_Set() const;
    bool is_root_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString drive_type;
    bool m_drive_type_isSet;
    bool m_drive_type_isValid;

    OAIIdentitySet owner;
    bool m_owner_isSet;
    bool m_owner_isValid;

    OAIQuota quota;
    bool m_quota_isSet;
    bool m_quota_isValid;

    QList<OAIDriveItem> items;
    bool m_items_isSet;
    bool m_items_isValid;

    OAIDriveItem root;
    bool m_root_isSet;
    bool m_root_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIDriveInline)

#endif // OAIDriveInline_H
