/**
 * Open Graph API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIDirectoryObject_allOf.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIDirectoryObject_allOf::OAIDirectoryObject_allOf(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIDirectoryObject_allOf::OAIDirectoryObject_allOf() {
    this->initializeModel();
}

OAIDirectoryObject_allOf::~OAIDirectoryObject_allOf() {}

void OAIDirectoryObject_allOf::initializeModel() {

    m_deleted_date_time_isSet = false;
    m_deleted_date_time_isValid = false;
}

void OAIDirectoryObject_allOf::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIDirectoryObject_allOf::fromJsonObject(QJsonObject json) {

    m_deleted_date_time_isValid = ::OpenAPI::fromJsonValue(deleted_date_time, json[QString("deletedDateTime")]);
    m_deleted_date_time_isSet = !json[QString("deletedDateTime")].isNull() && m_deleted_date_time_isValid;
}

QString OAIDirectoryObject_allOf::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIDirectoryObject_allOf::asJsonObject() const {
    QJsonObject obj;
    if (m_deleted_date_time_isSet) {
        obj.insert(QString("deletedDateTime"), ::OpenAPI::toJsonValue(deleted_date_time));
    }
    return obj;
}

QDateTime OAIDirectoryObject_allOf::getDeletedDateTime() const {
    return deleted_date_time;
}
void OAIDirectoryObject_allOf::setDeletedDateTime(const QDateTime &deleted_date_time) {
    this->deleted_date_time = deleted_date_time;
    this->m_deleted_date_time_isSet = true;
}

bool OAIDirectoryObject_allOf::is_deleted_date_time_Set() const{
    return m_deleted_date_time_isSet;
}

bool OAIDirectoryObject_allOf::is_deleted_date_time_Valid() const{
    return m_deleted_date_time_isValid;
}

bool OAIDirectoryObject_allOf::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_deleted_date_time_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIDirectoryObject_allOf::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
