/**
 * Open Graph API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIDirectoryObject_allOf.h
 *
 * Represents an Active Directory object. The directoryObject type is the base type for many other directory entity types.
 */

#ifndef OAIDirectoryObject_allOf_H
#define OAIDirectoryObject_allOf_H

#include <QJsonObject>

#include <QDateTime>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIDirectoryObject_allOf : public OAIObject {
public:
    OAIDirectoryObject_allOf();
    OAIDirectoryObject_allOf(QString json);
    ~OAIDirectoryObject_allOf() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QDateTime getDeletedDateTime() const;
    void setDeletedDateTime(const QDateTime &deleted_date_time);
    bool is_deleted_date_time_Set() const;
    bool is_deleted_date_time_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QDateTime deleted_date_time;
    bool m_deleted_date_time_isSet;
    bool m_deleted_date_time_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIDirectoryObject_allOf)

#endif // OAIDirectoryObject_allOf_H
