// model-body.mustache

// licenseInfo.mustache

/**
 * Libre Graph API
 * Libre Graph is a free API for cloud collaboration inspired by the MS Graph API.
 *
 * The version of the OpenAPI document: v1.0.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIEducationOrganization.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

class OAIEducationOrganizationPrivate {
    friend class OAIEducationOrganization;

     QString id;
     bool id_isSet;
     bool id_isValid;

     QString display_name;
     bool display_name_isSet;
     bool display_name_isValid;
};

OAIEducationOrganization::OAIEducationOrganization()
    : d_ptr()
{
}

OAIEducationOrganization::OAIEducationOrganization(const OAIEducationOrganization& other)
    : d_ptr(other.d_ptr)
{
}

OAIEducationOrganization::OAIEducationOrganization(QString json)
    : d_ptr(nullptr)
{
    this->fromJson(json);
}

OAIEducationOrganization::~OAIEducationOrganization() = default;

void OAIEducationOrganization::initializeModel() {
    if (d_ptr == nullptr) {
        d_ptr.reset(new OAIEducationOrganizationPrivate{});

        Q_D(OAIEducationOrganization);


        d->id_isSet = false;
        d->id_isValid = false;

        d->display_name_isSet = false;
        d->display_name_isValid = false;
    }
}

void OAIEducationOrganization::fromJson(QString jsonString) {
    QByteArray array(jsonString.toUtf8());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIEducationOrganization::fromJsonObject(QJsonObject json) {
    initializeModel();

    Q_D(OAIEducationOrganization);

    d->id_isValid = ::OpenAPI::fromJsonValue(d->id, json[QString("id")]);
    d->id_isSet = !json[QString("id")].isNull() && d->id_isValid;

    d->display_name_isValid = ::OpenAPI::fromJsonValue(d->display_name, json[QString("displayName")]);
    d->display_name_isSet = !json[QString("displayName")].isNull() && d->display_name_isValid;
}

QString OAIEducationOrganization::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIEducationOrganization::asJsonObject() const {
    Q_D(const OAIEducationOrganization);
    if(!d){
        return {};
    }
    QJsonObject obj;
    if (d->id_isSet) {
        obj.insert(QString("id"), ::OpenAPI::toJsonValue(d->id));
    }
    if (d->display_name_isSet) {
        obj.insert(QString("displayName"), ::OpenAPI::toJsonValue(d->display_name));
    }
    return obj;
}

QString OAIEducationOrganization::getId() const {
    Q_D(const OAIEducationOrganization);
    if(!d){
        return {};
    }
    return d->id;
}
void OAIEducationOrganization::setId(const QString &id) {
    Q_D(OAIEducationOrganization);
    Q_ASSERT(d);

    d->id = id;
    d->id_isSet = true;
}

bool OAIEducationOrganization::is_id_Set() const{
    Q_D(const OAIEducationOrganization);
    if(!d){
        return false;
    }

    return d->id_isSet;
}

bool OAIEducationOrganization::is_id_Valid() const{
    Q_D(const OAIEducationOrganization);
    if(!d){
        return false;
    }
    return d->id_isValid;
}

QString OAIEducationOrganization::getDisplayName() const {
    Q_D(const OAIEducationOrganization);
    if(!d){
        return {};
    }
    return d->display_name;
}
void OAIEducationOrganization::setDisplayName(const QString &display_name) {
    Q_D(OAIEducationOrganization);
    Q_ASSERT(d);

    d->display_name = display_name;
    d->display_name_isSet = true;
}

bool OAIEducationOrganization::is_display_name_Set() const{
    Q_D(const OAIEducationOrganization);
    if(!d){
        return false;
    }

    return d->display_name_isSet;
}

bool OAIEducationOrganization::is_display_name_Valid() const{
    Q_D(const OAIEducationOrganization);
    if(!d){
        return false;
    }
    return d->display_name_isValid;
}

bool OAIEducationOrganization::isSet() const {
    Q_D(const OAIEducationOrganization);
    if(!d){
        return false;
    }
    bool isObjectUpdated = false;
    do {
        if (d->id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (d->display_name_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIEducationOrganization::isValid() const {
    Q_D(const OAIEducationOrganization);
    if(!d){
        return false;
    }
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
