/**
 * Libre Graph API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.8.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIMember_Reference.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIMember_Reference::OAIMember_Reference(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIMember_Reference::OAIMember_Reference() {
    this->initializeModel();
}

OAIMember_Reference::~OAIMember_Reference() {}

void OAIMember_Reference::initializeModel() {

    m_odata_id_isSet = false;
    m_odata_id_isValid = false;
}

void OAIMember_Reference::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIMember_Reference::fromJsonObject(QJsonObject json) {

    m_odata_id_isValid = ::OpenAPI::fromJsonValue(odata_id, json[QString("@odata.id")]);
    m_odata_id_isSet = !json[QString("@odata.id")].isNull() && m_odata_id_isValid;
}

QString OAIMember_Reference::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIMember_Reference::asJsonObject() const {
    QJsonObject obj;
    if (m_odata_id_isSet) {
        obj.insert(QString("@odata.id"), ::OpenAPI::toJsonValue(odata_id));
    }
    return obj;
}

QString OAIMember_Reference::getOdataId() const {
    return odata_id;
}
void OAIMember_Reference::setOdataId(const QString &odata_id) {
    this->odata_id = odata_id;
    this->m_odata_id_isSet = true;
}

bool OAIMember_Reference::is_odata_id_Set() const{
    return m_odata_id_isSet;
}

bool OAIMember_Reference::is_odata_id_Valid() const{
    return m_odata_id_isValid;
}

bool OAIMember_Reference::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_odata_id_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIMember_Reference::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
