/**
 * Libre Graph API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0.5.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIOpenGraphFile.h
 *
 * File metadata, if the item is a file. Read-only.
 */

#ifndef OAIOpenGraphFile_H
#define OAIOpenGraphFile_H

#include <QJsonObject>

#include "OAIHashes.h"
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIOpenGraphFile : public OAIObject {
public:
    OAIOpenGraphFile();
    OAIOpenGraphFile(QString json);
    ~OAIOpenGraphFile() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    OAIHashes getHashes() const;
    void setHashes(const OAIHashes &hashes);
    bool is_hashes_Set() const;
    bool is_hashes_Valid() const;

    QString getMimeType() const;
    void setMimeType(const QString &mime_type);
    bool is_mime_type_Set() const;
    bool is_mime_type_Valid() const;

    bool isProcessingMetadata() const;
    void setProcessingMetadata(const bool &processing_metadata);
    bool is_processing_metadata_Set() const;
    bool is_processing_metadata_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    OAIHashes hashes;
    bool m_hashes_isSet;
    bool m_hashes_isValid;

    QString mime_type;
    bool m_mime_type_isSet;
    bool m_mime_type_isValid;

    bool processing_metadata;
    bool m_processing_metadata_isSet;
    bool m_processing_metadata_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIOpenGraphFile)

#endif // OAIOpenGraphFile_H
